### ISSUE TITLE
https://github.com/theajack/cnchar 开个头，留言的必回

### ISSUE THREAD

**Issue by theajack** [theajack/star-each-other#1]
[theajack/cnchar](https://github.com/theajack/cnchar)

开个头，留言的必回

诚信互赞

**Comment by zxc0254** [comment]
已给你star了

**Comment by theajack2** [comment]
@zxc0254 要我star你哪个仓库

**Comment by zxc0254** [comment]
> @zxc0254 要我star你哪个仓库

https://github.com/zxc0254/z.js

**Comment by zxc0254** [comment]
@theajack2 https://github.com/zxc0254/z.js

**Comment by theajack2** [comment]
@zxc0254 done

**Comment by zerosoul** [comment]
路过，我的开源作品集：https://works.yangerxiao.com/  挑感兴趣的star 即可

**Comment by icarus910** [comment]
互相follow 的来

**Comment by icarus910** [comment]
互相follow的有吗，你follow我我就follow你。

**Comment by Nirunfeng** [comment]
已经Star。https://github.com/Nirunfeng/face_beauty

**Comment by 18023785187** [comment]
https://github.com/18023785187/h-tools

**Comment by 18023785187** [comment]
@theajack  ： https://github.com/18023785187/h-tools
