### ISSUE TITLE
哥哥们,求赏个star,已点star, 留下仓库,互相点赞,必回

### ISSUE THREAD

**Issue by heart-to-the-sea** [theajack/star-each-other#17]
[heart-to-the-sea](https://github.com/heart-to-the-sea/heart-to-the-sea)

**Comment by theajack2** [comment]
@heart-to-the-sea 
已点 请回：[alinsjs](https://github.com/alinsjs/alins)

**Comment by heart-to-the-sea** [comment]
@theajack2 
已回
![image](https://user-images.githubusercontent.com/59409148/203511783-0aa31cfe-3551-42aa-ac76-d18093ec80b1.png)
