### ISSUE TITLE
有赞定回！诚信互赞！https://github.com/Autumn-one/a-calc-old

### ISSUE THREAD

**Issue by Autumn-one** [theajack/star-each-other#37]
https://github.com/Autumn-one/a-calc-old

**Comment by ischenliang** [comment]
已点，回我：https://github.com/ischenliang/quickly-picture-bed
![image](https://github.com/theajack/star-each-other/assets/115447272/891d46c7-9597-4d26-940d-33ee76d211cb)

**Comment by Autumn-one** [comment]
> 已点，回我：https://github.com/ischenliang/quickly-picture-bed ![image](https://private-user-images.githubusercontent.com/115447272/309982324-891d46c7-9597-4d26-940d-33ee76d211cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MTYwMTgsIm5iZiI6MTcwOTYxNTcxOCwicGF0aCI6Ii8xMTU0NDcyNzIvMzA5OTgyMzI0LTg5MWQ0NmM3LTk1OTctNGQyNi05NDBkLTMzZWU3NmQyMTFjYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNVQwNTE1MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZjljN2M4ZDcyNTc5NzdlZTM0NDMwMzU2Mzg2MGVhZWVlY2ZmNzFlZDA3Zjk1ZGEzY2E4YzE0MmM5MDJiYjg4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9ydaVR19Ali76bS24v-Gcq0DZEyeP86Za67UlEIdkWA)

已回

**Comment by adambone50** [comment]
已star，我的project是[https://github.com/Adamdad/hash3D] 感谢回star

**Comment by nebula-low-code** [comment]
已赞，求回赞，
https://github.com/nebula-low-code/Nebula-lowcode
https://gitee.com/Nebula-lowcode/nebulalowcode

**Comment by Autumn-one** [comment]
> 已赞，求回赞， https://github.com/nebula-low-code/Nebula-lowcode https://gitee.com/Nebula-lowcode/nebulalowcode

已回

**Comment by anyzz1** [comment]
可以用一些互赞平台, 例如 [GithubStar.Pro](https://githubstar.pro) 就蛮好用的，直接 Github 就能登陆，点 Star 后一小会就有回 Star 的.

**Comment by yibei333** [comment]
往这里瞧：https://github.com/yibei333/star-each-other ，有客户端支持，自动化处理

**Comment by Autumn-one** [comment]
> 往这里瞧：https://github.com/yibei333/star-each-other ，有客户端支持，自动化处理

？刷一堆消息？你是会做事的

**Comment by Autumn-one** [comment]
就tmd离谱

**Comment by yibei333** [comment]
大哥，你说的是对的，我已删除所有的评论，新开一个才是对的

**Comment by yibei333** [comment]
已star

**Comment by olcc78** [comment]
https://github.com/olcc78/start-to-study

<img width="1502" height="147" alt="Image" src="https://github.com/user-attachments/assets/3706577e-2eb0-4756-9c6a-10bf23893b30" />

**Comment by Autumn-one** [comment]
> https://github.com/olcc78/start-to-study
> 
> <img alt="Image" width="1502" height="147" src="https://private-user-images.githubusercontent.com/179694772/556068938-3706577e-2eb0-4756-9c6a-10bf23893b30.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzIzNDM4MDMsIm5iZiI6MTc3MjM0MzUwMywicGF0aCI6Ii8xNzk2OTQ3NzIvNTU2MDY4OTM4LTM3MDY1NzdlLTJlYjAtNDc1Ni05YzZhLTEwYmYyMzg5M2IzMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjYwMzAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI2MDMwMVQwNTM4MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NDBkM2ZlMmVjZTEyMGQ2NWU1NmIyYjFiZjk2MzVjOWNjOGQ1YTBmOTc5MTRiNDZmZjI4OWMxZjY5MTQ1ZjZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.J3iletF0hvFlvo5NVDDMW0oUn9eHl54JypC4SmYdmvo">

你这空项目没有star按钮
